// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnO4gPLIvpMyjejhT63qkLrpyffEm9jRQ',
    appId: '1:987502366121:web:951c5a907570444a2ec8b8',
    messagingSenderId: '987502366121',
    projectId: 'flutter-prep-583f0',
    authDomain: 'flutter-prep-583f0.firebaseapp.com',
    databaseURL: 'https://flutter-prep-583f0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-583f0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMQp5iE_GFZa4hEm7GXVQf69R4eEPgBk',
    appId: '1:987502366121:android:53a91e916fa0b0352ec8b8',
    messagingSenderId: '987502366121',
    projectId: 'flutter-prep-583f0',
    databaseURL: 'https://flutter-prep-583f0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-583f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKrnXCILuhzsiMoHHQCCyuxacG03o4Als',
    appId: '1:987502366121:ios:1cb9159272b8b3ab2ec8b8',
    messagingSenderId: '987502366121',
    projectId: 'flutter-prep-583f0',
    databaseURL: 'https://flutter-prep-583f0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-583f0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKrnXCILuhzsiMoHHQCCyuxacG03o4Als',
    appId: '1:987502366121:ios:1cb9159272b8b3ab2ec8b8',
    messagingSenderId: '987502366121',
    projectId: 'flutter-prep-583f0',
    databaseURL: 'https://flutter-prep-583f0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-583f0.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnO4gPLIvpMyjejhT63qkLrpyffEm9jRQ',
    appId: '1:987502366121:web:277aaf6d0e037f712ec8b8',
    messagingSenderId: '987502366121',
    projectId: 'flutter-prep-583f0',
    authDomain: 'flutter-prep-583f0.firebaseapp.com',
    databaseURL: 'https://flutter-prep-583f0-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-prep-583f0.firebasestorage.app',
  );
}